#Deployment PostgreSQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:14.3
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "kubenews"
        - name: POSTGRES_PASSWORD
          value: "Kubenews@123!"
        - name: POSTGRES_DB
          value: "kubenews_db"
---

apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: postgresql
  ports:
  - port: 5432
    targetPort: 5432
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenews
spec:
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels:
        app: kubenews
    spec:
      containers:
      - name: kubenews
        image: trodriguesr861320/kube-news:v1
        env:
        - name: DB_USERNAME
          value: "kubenews"
        - name: DB_PASSWORD
          value: "Kubenews@123!"
        - name: DB_DATABASE
          value: "kubenews_db"
        - name: DB_HOST
          value: "postgresql"
---

apiVersion: v1
kind: Service
metadata:
  name: kube-news
spec:
  selector:
    app: kubenews
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: NodePort
